server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:yuzhishuishui/springcloud2020-config.git #ssh链接
#          uri:  https://github.com/yuzhishuishui/springcloud2020-config.git #https链接
          uri: https://github.com/yuzhishuishui/study2020-springcloud.git
          ####搜索目录
          search-paths:
#            - springcloud2020-config
            - cloud-common-config
          skip-ssl-validation: true
      ####读取分支
      label: master
##rabbitmq相关配置
#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/

###rabbitmq相关配置,暴露bus刷新配置的端点
#management:
#  endpoints: #暴露bus刷新配置的端点
#    web:
#      exposure:
#        include: 'bus-refresh'
