server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment

  cloud:
    consul:
      host: 182.92.104.245
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://${spring.cloud.consul.host}:${spring.cloud.consul.port}
